// <auto-generated />
namespace BDD_ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AddIntervention : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIntervention));
        
        string IMigrationMetadata.Id
        {
            get { return "201911121342226_Add-Intervention"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
